version: '3.8'
services:
  messenger-server:
    container_name: messenger-server
    platform: linux/x86_64
    build:
      context: ./server/
      target: development
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9240:9240
    volumes:
      - ./server:/home/messenger/server
      - /home/messenger/server/node_modules
    working_dir: /home/messenger/server
    restart: on-failure
    depends_on:
      - messenger-db
  messenger-db:
    container_name: messenger-db
    image: postgres
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
